# 예외 & 에러 처리	

> 2019-11-03 (작성자: 강민)



### 프리뷰

- 어떠한 웹 페이지에서 예기치 못한 오류나 예외 상황들이 발생할 수 있다. 이러한 상황도 사용자 입장에서도 알아야 하기 때문에 오류/예외 상황을 알려주는 페이지를 보여줌으로써 사용자 기반의 웹 서비스를 제공하고 있다. 그렇다면 지금 프로젝트를 진행하고 있는 시점에서 어떠한 오류가 났고 이 오류 상황을 어떻게 처리되어야 할 지 생각해 보자



### 예외처리

- 예외처리란 프로그램이 실행되는 동안 문제가 발생할 때 대처할 수 있게 처리하는 것이다.
- 발생하는 문제는 예외(Exception)과 에러(Error)로 분류된다.
  - 예외(Exception): 프로그램 실행 중 발생하는 오류
  - 오류(Error): 프로그래밍 언어의 문법적인 오류
- 문제가 생기는 이유는 일반적으로 잘못된 코드를 작성했거나, 사용자가 개발자의 의도와 다르게 프로그램을 사용한 이유 등 여러가지로 존재한다.
- 이를 기본 예외 처리와 고급 예외 처리로 해결할 수 있다.
  - 기본 예외 처리: 예외가 발생하지 않게 사전에 해결, 조건문으로 처리할 수 있음.
  - 고급 예외 처리: 예외가 발생하면 그 예외를 잡아서 해결



### 고급 예외 처리 (try/catch/finally/throw)

- 주로 사용하고 있는 Javascript에서 고급 예외 처리를 try/catch/finally 구문과 throw로 해결이 가능하다

- try: 예외가 발생할 지도 모르는 코드 블록들을 정의하는 공간 (일단 시도해본다)

- catch: try안에서 예외가 발생한 경우, 그 예외를 처리하는 공간 (예외를 잡는다)

- finally: catch이후 예외와 상관없이 실행해야 하는 공간 (끝끝내 해야 한다) 

- throw: 예외를 강제적으로 발생시킨다. (예외를 가까운 예외처리 부분으로 던진다)

  ```javascript
  try { 
      /**
       * 정상이라면 이 코드는 아무런 문제없이 블록의 시작부터 끝까지 실행된다.
       * 하지만 경우에 따라 예외가 발생할 수 있다.
       * 예외는 throw 문에 의해 직접적으로 발생할 수도 있고,
       * 또는 예외를 발생시키는 메서드의 호출에 의해 발생할 수도 있다.
       */ 
  } catch (e) { 
      /**
       * 이 블록 내부의 문장들은 오직 try 블록에서 예외가 발생할 경우에만 실행된다.
       * 이 문장들에선 지역 변수 e를 사용하여 Error 객체 또는 앞에서 던진 다른 값을 참조할 수 있다.
       * 이 블록에서는 어떻게든 그 예외를 처리할 수도 있고,
       * 그냥 아무것도 하지 않고 예외를 무시할 수도 있고,
       * 아니면 throw 를 사용해서 예외를 다시 발생시킬 수도 있다.
       */
  } finally {
      /** 
       * 이 블록에는 try 블록에서 일어난 일에 관계없이 무조건 실행될 코드가 위치한다.
       * 이 코드는 try 블록이 어떻게든 종료되면 실행된다.
       * try 블록이 종료되는 상황은 다음과 같다.
       * 1) 정상적으로 블록의 끝에 도달했을 때
       * 2) break, continue 또는 return 문에 의해서
       * 3) 예외가 발생했지만 catch 절에서 처리했을 때
       * 4) 예외가 발생했고 그것이 잡히지 않은 채 퍼져나갈 때
       */ 
  }
  
  ```

  

### 이를 현재 진행 중인 프로젝트에 적용시켜본다면...??

- 현재 우리는 프로젝트를 진행하면서 vuex와 firebase를 적용하고 있다. 이를 적용하는 데 사용하는 언어는 javascript이므로 웹 사이트의 예외 처리를 할 수 있을 것이다. 근데... 어떻게?

- 현재 프로젝트 구조를 간략화한다면 아래 구조일 것이다.

  ```
  APP
   |
   └-- view
   	   |
   	   └-- components
   	   			|
   	   			└-- Vuex(store)
   	   					|
   	   					└-- state
   	   					|
   	   					└-- getters
   	   					|
   	   					└-- mutations
   	   					|
   	   					└-- actions
   	   							|
   	   							└-- firebase API
   	   							|
   	   							└-- kakaomap API
  ```

  사용자들이 사용하고 있는 뷰안에 여러 컴퍼넌트들이 존재하고 그 컴퍼넌트들은 vuex(store)를 바라보고 있고 vuex는 데이터 상태(state), 상태들을 가져오는 getters, state를 변경하는 mutations, 그리고 mutation을 작동시키는 actions로 이루어져 있다. 여기서 actions에서 firebase API를 사용함으로써 DB에 접근하고 state를 반영하고 있다.

- 즉, APP - View - Component - store - **firebase API & kakaomap API** - store - component - view - app 순으로 데이터가 진행 될 것이다.
- firebase API와 kakaomap API에서 나는 예외 상황들을 try-catch-throw를 통해 상단의 vuex의 예외처리 부분으로 던질 수 있고, vuex(특히 actions 부분)에서 이 예외상황을 이어받아 상단의 component로 전달 할 수 있다. 마지막으로 component가 예외상황을 받으면 그 예외 상황을 처리하는 페이지로 넘어가게 끔, 유도해주면 될 수 있다.
- 작성시간 기준(2019-11-03)으로 코드를 확인한 결과 firebase API에서 try-catch를 통해 예외를 throw를 하고 있음을 확인하였고 (몇몇 부분 제외), vuex(store)의 actions에서도 대부분 try-catch를 통해 예외를 throw를 하고 있다. **그렇다면 vuex가 쏘아올린 예외는 어디에 있는 것일까?** 

- 로그인이나 랜덤닉네임관련 컴퍼넌트에도 try-catch를 하고는 있다. 하지만 중요한 건 **catch** 부분이다. 이 catch부분에서 어떠한 예외페이지로 보내는 vue-router.push가 있어야 할 것이다. 물론 예외페이지도 만들어야 할 것이다.
- 그 외 다른 컴퍼넌트, 특히 채팅과 맵리스트, 그리고 kakaomap API를 사용하는 컴퍼넌트들도 위와 같이 처리해주면서 예외페이지로 넘어가게 만드는 catch부분이 필요할 것으로 보인다.



### 예외페이지가 받을 에러들

- 이 프로젝트에서 생길 수 있는 에러들은 크게 3가지로 구분지을 수 있다고 생각한다.

  - 서비스 사용에서의 에러
  - <a href="https://firebase.google.com/docs/reference/js/firebase.firestore.html#firestoreerrorcode">firebase의 에러</a>
  - kakaomap의 에러

  서비스 사용에서의 에러는 없는 페이지로 가는 에러(404)나 시간 초과 등 사용자 사용 과정에서 일어날 수 있음직 한 에러들이다. firebase와 kakaomap의 에러는 관련 API를 사용하면서 발생하는 에러로 따로 관련 API reference에 명시를 하고 있다.

- 이러한 오류들을 받아들이는 파라미터들을 case by case로 나눠서 해동 오류를 보여줌으로써 예외 처리를 마무리 할 수 있다고 생각한다.
- 그리고, 개인적으로 이러한 오류 발생 가능성을 생각하는 것은 초기에 생각을 했어야 하는 아쉬움이 있다. 이러한 프로젝트와 같은 프로젝트를 만들시, 오류를 테스트하는 공간을 따로 만들어 처리한다면, 예외처리 노하우를 쉽게 익힐 수 있을 것이다.



출처

 https://dimitrioslytras.com/blog/vue-error-handling/ 



